#install.packages("XML")
library("XML")
library("readxl")


setwd("C:\\Users\\Hurchins Manua\\Downloads\\Decoded Forms\\Decoded forms\\Kenya forms\\Nawiri\\NW PPI Targetting Form")
results <- xmlToDataFrame("a0a2I00000SYsDsQAL_2023-02-06_11-26-35.xml", homogeneous = NA,
                          collectNames = TRUE, nodes = list(),
                          stringsAsFactors = FALSE)


results[is.na(results)] <- ""
results$no<-1
library(data.table)
setDT(results)
results<-results[, lapply(.SD, paste0, collapse=""), by=no]



##### Working from Prototype to now create loop to append data  ##################


files <- list.files(pattern = "\\.xml$")
result <- xmlToDataFrame(files[1], homogeneous = NA,
                          collectNames = TRUE, nodes = list(),
                          stringsAsFactors = FALSE)
##Clean the data 

result[is.na(result)] <- ""
result$no<-1
library(data.table)
setDT(result)
result<-result[, lapply(.SD, paste0, collapse=""), by=no]




#reading each file within the range and append them to create one file
  for (f in files[-1]){
     
  resultz <- xmlToDataFrame(f, homogeneous = NA,
                            collectNames = TRUE, nodes = list(),
                            stringsAsFactors = FALSE)        # read the file
  
  resultz[is.na(resultz)] <- ""
  resultz$no<-1
  setDT(resultz)
  resultz<-resultz[, lapply(.SD, paste0, collapse=""), by=no]
  result <- rbind(result, resultz, fill=TRUE) 
    
}
result<-subset(result,select=-no)

##Replacing TW ids.

result <- apply(result, 2, function(x) ifelse(x == "a0I2I00000aTQoKUAW", "Laisamis", x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQoJUAW","isiolo",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQoJUAW","Isiolo",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQoTUAW","Marsabit",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQlsUAG","Moyale",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQltUAG","North Horr",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQluUAG","Saku",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQlvUAG","Garbatulla",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQlwUAG","Isiolo",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQlxUAG","Merti",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQoKUAW","Laisamis",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQlyUAG","Dukana",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQlzUAG","Golbo",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQm0UAG","Heillu/Manyatta",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQm1UAG","Illeret",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQm2UAG","Karare",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQm3UAG","Kargi/South Horr",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQm4UAG","Korr/Ngurunit",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQm5UAG","Laisamis",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQm6UAG","Loglogo",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQm7UAG","Loiyangalani",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQm8UAG","Maikona",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQm9UAG","Marsabit Central",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmAUAW","Moyale Township",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmBUAW","North Horr",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmCUAW","Obbu",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmDUAW","Sagante/Jaldesa",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmEUAW","Turbi",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmFUAW","Uran",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmGUAW","Bulla Pesa",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmHUAW","Burat",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmIUAW","Chari",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmJUAW","Cherab",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmKUAW","Garba Tulla",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmLUAW","Kinna",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmMUAW","Ngare Mara",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmNUAW","Oldo/Nyiro",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmOUAW","Sericho",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmPUAW","Wabera",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQoFUAW","Butiye",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQoaUAG","Targeting",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmaUAG","Household refused to participate",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmbUAG","Household relocated",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmcUAG","Other",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmdUAG","NOT APPLICABLE - THE PPI IS BEING COLLECTED",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQoIUAW","Household not located",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmeUAG","No",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQoeUAG","Yes",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmQUAW","Son",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmRUAW","Daughter",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmSUAW","Niece",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmTUAW","Nephew",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmUUAW","Mother",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmVUAW","Father",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmWUAW","Friend",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmXUAW","Other",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmgUAG","Sibling",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQoZUAW","Spouse",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmYUAW","No",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQofUAG","Yes",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmZUAW","No",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQogUAG","Yes",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmfUAG","Female",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQoQUAW","Male",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQoCUAW","Single",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQoDUAW","Divorced",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQoEUAW","Separated",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQoSUAW","Married",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQodUAG","Widowed",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQoBUAW","No",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQohUAG","Yes",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmlUAG","No",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQoiUAG","Yes",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmhUAG","No",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQojUAG","Yes",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmiUAG","No",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQokUAG","Yes",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmkUAG","No",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQolUAG","Yes",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmmUAG","No",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQomUAG","Yes",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmnUAG","Kwale",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmoUAG","Kilifi",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmpUAG","Tana River",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmqUAG","Lamu",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmrUAG","Taita Taveta",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmsUAG","Garissa",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmtUAG","Wajir",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmuUAG","Mandera",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmvUAG","Marsabit",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmwUAG","Isiolo",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmxUAG","Meru",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmyUAG","Vihiga",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmzUAG","Tharaka Nithi",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQn0UAG","Bungoma",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQn1UAG","Embu",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQn2UAG","Busia",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQn3UAG","Kitui",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQn4UAG","Siaya",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQn5UAG","Machakos",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQn6UAG","Kisumu",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQn7UAG","Makueni",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQn8UAG","Homa Bay",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQn9UAG","Nyandarua",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQnAUAW","Migori",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQnBUAW","Nyeri",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQnCUAW","Kisii",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQnDUAW","Kirinyaga",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQnEUAW","Nyamira",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQnFUAW","Nairobi",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQnGUAW","Muranga",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQnHUAW","Kiambu",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQnIUAW","Turkana",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQnJUAW","West Pokot",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQnKUAW","Samburu",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQnLUAW","Trans Nzoia",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQnMUAW","Uasin Gishu",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQnNUAW","Elgeyo Marakwet",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQnPUAW","Nandi",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQnRUAW","Baringo",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQnTUAW","Laikipia",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQnVUAW","Nakuru",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQnWUAW","Narok",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQnYUAW","Kaijiado",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQnaUAG","Kericho",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQncUAG","Bomet",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQndUAG","Kakamega",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQoUUAW","Mombasa",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQnOUAW","Primary",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQnQUAW","Secondary or post-primary, vocational",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQnSUAW","College level or higher",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQnUUAW","There is no female household head/spouse",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQoXUAW","Pre-primary, none, or other",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQnXUAW","Primary",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQnZUAW","Secondary or post-primary, vocational",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQnbUAG","College level or higher",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQoYUAW","Pre-primary, none, or other",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQneUAG","No",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQonUAG","Yes",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQnfUAG","No",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQooUAG","Yes",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQngUAG","No",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQopUAG","Yes",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQnjUAG","No",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQoqUAG","Yes",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQnoUAG","No",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQorUAG","Yes",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQnrUAG","Uncovered adobe, plywood, cardboard, reused wood, or corrugated iron sheets",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQoHUAW","Finished walls (cement, stone with lime/cement, bricks, cement blocks, covered adobe, or wood planks/shingles)",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQoWUAW","Natural walls (cane/palm/trunks, grass/reeds, or mud/cow dung), no walls, bamboo with mud, stone with mud, or other)",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQntUAG","Other (including wood planks/shingles, parquet or polished wood, vinyl or asphalt strips, ceramic tiles, cement, or carpet)",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQoVUAW","Natural floor (earth/sand or dung) or palm/bamboo",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQoPUAW","Less than 6",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQocUAG","6 or more",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQnvUAG","Female",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQoRUAW","Male",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQnwUAG","No",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQosUAG","Yes",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQnxUAG","No",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQotUAG","Yes",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQnhUAG","3 meals a day",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQnuUAG","2 meals a day",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQobUAG","0-1 meals a day",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQnyUAG","No",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQouUAG","Yes",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQnzUAG","No",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQovUAG","Yes",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQoAUAW","No",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQowUAG","Yes",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQo0UAG","No",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQoxUAG","Yes",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQo1UAG","No",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQoyUAG","Yes",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQo3UAG","No",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQozUAG","Yes",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQo6UAG","No",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQp0UAG","Yes",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQo8UAG","No",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQp1UAG","Yes",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQo2UAG","No",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQp2UAG","Yes",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQo4UAG","No",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQp3UAG","Yes",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQo5UAG","No",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQp4UAG","Yes",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQo7UAG","No",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQp5UAG","Yes",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQniUAG","Government welfare/safety nets",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQnkUAG","Livestock trading",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQnlUAG","Employment",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQnmUAG","None of the above",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQoGUAW","Donations",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQnnUAG","3,000 to 6,000 KES",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQnpUAG","More than 6,000 KES",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQoNUAW","Less than 3,000 KES",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQnqUAG","15 or more cattle",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQoLUAW","Less than 15 cattle",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQnsUAG","30 or more shoats",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQoOUAW","Less than 30 shoats",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQo9UAG","3 and more",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQoMUAW","less than 3",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQmjUAG","No",x))
result <- apply(result, 2, function(x)ifelse(x == "a0I2I00000aTQp6UAG","Yes",x))


result<-as.data.frame(result)
result[is.na(result)] <- ""
library(openxlsx)

#writing the appended file

wb <- createWorkbook()
addWorksheet(wb, "My Data")
writeData(wb, "My Data", result)
saveWorkbook(wb, "my_data.xlsx", overwrite = TRUE)
 

#write.csv(result, "PPI_Nawiri_appended7.csv", row.names=FALSE, quote=FALSE)  
  
  
  
  
